/* =========================================================
   Séville · 30 sept → 3 oct 2026 — données du guide
   Pour ajouter un lieu : copier un bloc dans PLACES
   (id unique, cat, lat/lng) puis le citer dans DAYS.
   ========================================================= */

const CATEGORIES = {
  base:     { label: "Notre base",      color: "#1f2a44", icon: "⌂" },
  monument: { label: "Incontournables", color: "#1f5f8b", icon: "★" },
  tapas:    { label: "Tapas & bodegas", color: "#b5452b", icon: "🍷" },
  table:    { label: "Belles tables",   color: "#7a2e52", icon: "🍽" },
  nuit:     { label: "Flamenco & nuit", color: "#6b4fa3", icon: "♪" },
  marche:   { label: "Marchés",         color: "#2f7d4f", icon: "◆" }
};

const PLACES = [
  // ---------- BASE ----------
  { id: "apt", cat: "base", name: "Espíritu Santo Suite Apartment", area: "San Julián / Feria",
    lat: 37.39559, lng: -5.99026,
    desc: "Notre appartement, calle Espíritu Santo, en plein quartier vivant du nord du centre historique. Calle Feria, l’Alameda et Palacio de las Dueñas à 5 min à pied, Giralda à 20 min.",
    tip: "Check-in officiel 15h–20h : prévenir l’hôte de notre arrivée tardive mercredi soir." },

  // ---------- INCONTOURNABLES ----------
  { id: "alcazar", cat: "monument", name: "Real Alcázar", area: "Santa Cruz",
    lat: 37.38321, lng: -5.99018,
    desc: "Palais royal mudéjar encore en usage, patios, azulejos et jardins immenses. Le monument n°1 de Séville.",
    tip: "Octobre : 9h30–17h. Billet 15,50 € (+5,50 € Cuarto Real Alto, les appartements royaux). Réserver le créneau de 9h30 sur le site officiel uniquement.",
    url: "https://alcazarsevilla.org/" },
  { id: "catedral", cat: "monument", name: "Cathédrale & Giralda", area: "Centro",
    lat: 37.38591, lng: -5.99314,
    desc: "La plus grande cathédrale gothique du monde, tombeau de Colomb, et la montée de la Giralda (rampes, pas de marches) pour la vue.",
    tip: "Lun–sam 10h45–19h. 13 € en ligne (14 € sur place), Giralda + église du Salvador incluses. Visite des toits en option (20 €).",
    url: "https://catedraldesevilla.servitickets.es/" },
  { id: "salvador", cat: "monument", name: "Église du Salvador", area: "Centro",
    lat: 37.39007, lng: -5.99269,
    desc: "Deuxième plus grande église de Séville, retables baroques dorés spectaculaires. La place devant est LE lieu de l’apéro sévillan.",
    tip: "Incluse dans le billet Cathédrale — gardez-le." },
  { id: "espana", cat: "monument", name: "Plaza de España", area: "Parque de María Luisa",
    lat: 37.37658, lng: -5.98600,
    desc: "Hémicycle de brique et d’azulejos de l’Expo 1929, bancs des provinces, canal. Spectaculaire en fin de journée.",
    tip: "Gratuit. Éviter les vendeurs d’éventails et de romarin." },
  { id: "mariluisa", cat: "monument", name: "Parque de María Luisa", area: "Sud",
    lat: 37.37477, lng: -5.98879,
    desc: "Le grand parc romantique : fontaines, glorietas, ombre. À combiner avec la Plaza de España." },
  { id: "setas", cat: "monument", name: "Setas de Sevilla (Metropol Parasol)", area: "Encarnación",
    lat: 37.39340, lng: -5.99192,
    desc: "La structure en bois contemporaine ; passerelle panoramique au sommet. Idéal au coucher du soleil (~19h45 début octobre).",
    tip: "Billet pour la passerelle sur place ou en ligne. Ruines romaines (Antiquarium) au sous-sol." },
  { id: "pilatos", cat: "monument", name: "Casa de Pilatos", area: "San Bartolomé",
    lat: 37.39024, lng: -5.98725,
    desc: "Palais andalou privé (ducs de Medinaceli), mélange mudéjar-Renaissance, patio sublime. Moins de monde que l’Alcázar.",
    tip: "Souvent au programme de la Noche en Blanco." },
  { id: "duenas", cat: "monument", name: "Palacio de las Dueñas", area: "San Juan de la Palma",
    lat: 37.39538, lng: -5.98941,
    desc: "Palais des ducs d’Albe, patios, bougainvilliers, collection d’art. À 3 minutes de l’appartement.",
    tip: "Idéal jeudi en fin de matinée après le marché." },
  { id: "macarena", cat: "monument", name: "Basílica de la Macarena & murailles", area: "Macarena",
    lat: 37.40245, lng: -5.98943,
    desc: "La Vierge la plus vénérée de Séville et le plus beau tronçon des murailles almohades. Quartier populaire authentique." },
  { id: "alameda", cat: "monument", name: "Alameda de Hércules", area: "Alameda",
    lat: 37.39888, lng: -5.99374,
    desc: "Grande place-promenade bordée de terrasses, fréquentée par les Sévillans de tous âges le soir. Notre QG pour la dernière copa." },
  { id: "torreoro", cat: "monument", name: "Torre del Oro & bords du Guadalquivir", area: "Arenal",
    lat: 37.38240, lng: -5.99632,
    desc: "Tour almohade du XIIIe s. au bord du fleuve. Balade le long du Paseo de Colón jusqu’au pont de Triana." },
  { id: "maestranza", cat: "monument", name: "Plaza de Toros de la Maestranza", area: "Arenal",
    lat: 37.38596, lng: -5.99842,
    desc: "Arène baroque mythique, vue depuis le quai. Visite guidée possible (30 min)." },
  { id: "isabel", cat: "monument", name: "Pont de Triana & Calle Betis", area: "Triana",
    lat: 37.38628, lng: -6.00243,
    desc: "Traverser le pont Isabel II au coucher du soleil, puis longer la Calle Betis côté Triana, le quartier des céramistes et du flamenco." },
  { id: "ayto", cat: "monument", name: "Ayuntamiento (Hôtel de ville)", area: "Plaza Nueva",
    lat: 37.38868, lng: -5.99448,
    desc: "Façade plateresque ; lieu régulier de la Noche en Blanco (visites nocturnes)." },

  // ---------- MARCHÉS ----------
  { id: "jueves", cat: "marche", name: "Mercadillo « El Jueves »", area: "Calle Feria",
    lat: 37.39870, lng: -5.99160,
    desc: "Le plus vieux marché aux puces de Séville (depuis le XIIIe s. !), chaque jeudi sur la calle Feria : brocante, vieux azulejos, affiches de Semana Santa, vinyles, bric-à-brac.",
    tip: "Jeudi 8h–15h. Y aller avant 10h30 pour les meilleures trouvailles. Espèces, et on négocie." },
  { id: "feria_mkt", cat: "marche", name: "Mercado de Feria", area: "Calle Feria",
    lat: 37.39951, lng: -5.99154,
    desc: "Marché couvert de quartier, étals de poisson et petits bars à l’intérieur où les habitués prennent une caña et une assiette de fruits de mer vers midi.",
    tip: "Parfait pour enchaîner après El Jueves." },
  { id: "triana_mkt", cat: "marche", name: "Mercado de Triana", area: "Triana",
    lat: 37.38575, lng: -6.00355,
    desc: "Marché couvert au pied du pont, construit sur les ruines du château de l’Inquisition. Étals + comptoirs à tapas.",
    tip: "Le matin pour l’ambiance marché, fermé le dimanche." },

  // ---------- TAPAS & BODEGAS ----------
  { id: "rinconcillo", cat: "tapas", name: "El Rinconcillo", area: "Santa Catalina", addr: "Calle Gerona 40",
    lat: 37.39334, lng: -5.98829,
    desc: "Le plus vieux bar de Séville (1670). Comptoir en acajou, l’addition à la craie. Célèbre, mais les Sévillans y viennent toujours.",
    order: "Espinacas con garbanzos, croquetas, bacalao, un fino." },
  { id: "eslava", cat: "tapas", name: "Eslava", area: "San Lorenzo", addr: "Calle Eslava 3",
    lat: 37.39755, lng: -5.99692,
    desc: "La référence de la tapa créative, plébiscitée par les locaux. Bar à tapas + salle restaurant (réservable).",
    order: "Cigarro para Bécquer, huevo sobre bizcocho de boletus, costilla a la miel de caña.",
    tip: "Mar–sam 12h30–00h, fermé lundi. Réserver la salle (954 90 65 68) ou arriver à l’ouverture du soir (~20h15)." },
  { id: "ricardo", cat: "tapas", name: "Casa Ricardo", area: "San Lorenzo", addr: "Calle Hernán Cortés 2",
    lat: 37.39759, lng: -5.99587,
    desc: "Bar de quartier décoré d’images de confréries, ambiance 100 % sévillane.",
    order: "Croquetas de jamón (parmi les meilleures de la ville), solomillo al whisky." },
  { id: "duo", cat: "tapas", name: "Dúo Tapas", area: "Alameda", addr: "Calle Calatrava 10",
    lat: 37.40136, lng: -5.99386,
    desc: "Petit bar moderne au nord de l’Alameda, tapas fusion généreuses, clientèle de quartier.",
    order: "Arroz del día, tataki, croquetas de rabo de toro." },
  { id: "antojo", cat: "tapas", name: "Bar Antojo", area: "Alameda", addr: "Calle Calatrava 44",
    lat: 37.40290, lng: -5.99487,
    desc: "Tapas d’auteur à prix doux, très fréquenté par les trentenaires/quadras du quartier.",
    tip: "Bonne option pour le dîner tardif du mercredi." },
  { id: "yebra", cat: "tapas", name: "Bar Yebra", area: "Macarena", addr: "Calle Medalla Milagrosa 3",
    lat: 37.40140, lng: -5.98232,
    desc: "Bar gastronomique de quartier, zéro touriste, cuisine de marché soignée.",
    order: "Merluza sobre fetuccini negro, guisos du jour." },
  { id: "cateca", cat: "tapas", name: "Taberna Manolo Cateca", area: "Centro", addr: "Calle Santa María de Gracia 13",
    lat: 37.39241, lng: -5.99468,
    desc: "Taverne de 1920 (ex-« La Goleta ») tapissée de bouteilles : vins de Jerez, conserves, charcuterie, fromages.",
    order: "Une manzanilla en rama ou un amontillado avec chacina.",
    tip: "Lun–sam à partir de midi." },
  { id: "dosmayo", cat: "tapas", name: "Bodega Dos de Mayo", area: "Plaza de la Gavidia", addr: "Plaza de la Gavidia 6",
    lat: 37.39513, lng: -5.99710,
    desc: "Grande bodega classique avec terrasse sur une place calme, qualité régulière, très locale.",
    order: "Ensaladilla de pulpo, pescado frito, carrillada." },
  { id: "romero", cat: "tapas", name: "Bodeguita Romero", area: "Arenal", addr: "Calle Harinas 10",
    lat: 37.38704, lng: -5.99570,
    desc: "Institution pour une chose : le montadito de pringá (viandes de puchero fondantes dans un petit pain).",
    order: "Montadito de pringá + manzanilla, papas aliñás." },
  { id: "morales", cat: "tapas", name: "Casa Morales", area: "Arenal", addr: "Calle García de Vinuesa 11",
    lat: 37.38653, lng: -5.99461,
    desc: "Bodega de 1850 avec d’immenses jarres (tinajas) dans l’arrière-salle. Ardoise de tapas simples.",
    order: "Un fino, chacinas, montaditos." },
  { id: "cerrillo", cat: "tapas", name: "Blanco Cerrillo", area: "Centro", addr: "Calle José de Velilla 1",
    lat: 37.39133, lng: -5.99560,
    desc: "Freiduría-bar debout, ultra-local. Rapide, pas cher, parfait.",
    order: "Boquerones en adobo (la spécialité), cazón." },
  { id: "kiko", cat: "tapas", name: "Kiko de la Chari", area: "Centro", addr: "Calle Herbolarios 17",
    lat: 37.39024, lng: -5.99178,
    desc: "Cuisine de ragoûts « comme à la maison », public d’habitués.",
    order: "Guisos du jour (carrillada, menudo, garbanzos).",
    tip: "Espèces uniquement." },
  { id: "teresas", cat: "tapas", name: "Las Teresas", area: "Santa Cruz", addr: "Calle Santa Teresa 2",
    lat: 37.38598, lng: -5.98932,
    desc: "Ancienne épicerie de 1870 : jambons suspendus, azulejos, jamón coupé au couteau. Le seul bar de Santa Cruz qu’on garde.",
    order: "Jamón ibérico, queso viejo, un fino bien frais." },
  { id: "fresquita", cat: "tapas", name: "Taberna La Fresquita", area: "Santa Cruz", addr: "Calle Mateos Gago 29",
    lat: 37.38662, lng: -5.98992,
    desc: "Minuscule bar cofrade (images de Semana Santa partout), on boit dehors sur les rebords.",
    order: "Une caña ou un vermut et une tapa de chicharrones." },
  { id: "golondrinas", cat: "tapas", name: "Las Golondrinas", area: "Triana", addr: "Calle Antillano Campos 26",
    lat: 37.38487, lng: -6.00551,
    desc: "Bar de Triana aux azulejos, toujours plein de Trianeros.",
    order: "Punta de solomillo, champiñones, caballito de jamón." },
  { id: "mercader", cat: "tapas", name: "El Mercader de Triana", area: "Triana", addr: "Calle Antillano Campos 15",
    lat: 37.38496, lng: -6.00502,
    desc: "Bar à vins de Triana, belle carte andalouse et cuisine soignée.",
    order: "Pulpo, papas aliñás, un vin blanc de l’Aljarafe." },
  { id: "ruperto", cat: "tapas", name: "Casa Ruperto", area: "Triana", addr: "Avenida Santa Cecilia 2",
    lat: 37.38188, lng: -6.00858,
    desc: "Bar de quartier mythique pour une seule spécialité, à l’écart du flux touristique.",
    order: "Codorniz frita (caille frite) et une bière." },
  { id: "puertacarne", cat: "tapas", name: "Freiduría Puerta de la Carne", area: "Santa María la Blanca", addr: "Calle Santa María la Blanca 34",
    lat: 37.38590, lng: -5.98693,
    desc: "Poisson frit au cornet, en terrasse. Simple et bon.",
    order: "Surtido de pescado frito (adobo, puntillitas, calamar)." },
  { id: "comercio", cat: "tapas", name: "Bar El Comercio", area: "Centro", addr: "Calle Lineros 9",
    lat: 37.39076, lng: -5.99228,
    desc: "Bar de 1904 pour le petit-déjeuner sévillan : churros + chocolat au comptoir.",
    order: "Churros con chocolate, ou tostada con tomate y aceite." },

  // ---------- BELLES TABLES ----------
  { id: "sobretablas", cat: "table", name: "Sobretablas", area: "El Porvenir", addr: "Calle Colombia 7",
    lat: 37.36975, lng: -5.98453,
    desc: "Guide Michelin, couple passé par El Celler de Can Roca. Cuisine andalouse revisitée et l’une des meilleures cartes de vins de Jerez de la province. À 5 min de la Plaza de España.",
    order: "Carabineros con chicharrones, menu dégustation avec accords de Jerez.",
    tip: "Mar–sam 13h45–16h30 / 20h15–23h. Réserver le samedi midi : sobretablasrestaurante.com / +34 955 54 64 51.",
    url: "https://sobretablasrestaurante.com/" },

  // ---------- FLAMENCO & NUIT ----------
  { id: "torresmac", cat: "nuit", name: "Peña Flamenca Torres Macarena", area: "Macarena", addr: "Calle Torrijiano 29",
    lat: 37.40430, lng: -5.99069,
    desc: "Vraie peña (club d’aficionados) : chaque JEUDI, tertulia flamenca à partir de 20h. Public de connaisseurs, bar associatif, zéro mise en scène. À 10 min à pied de l’appartement.",
    tip: "Entrée libre ou très modique, consommation au bar. Arriver vers 20h30 ; être discret pendant le chant.",
    url: "http://www.torresmacarena.com/" },
  { id: "carboneria", cat: "nuit", name: "La Carbonería", area: "Santa Cruz", addr: "Calle Levíes 18",
    lat: 37.38776, lng: -5.98725,
    desc: "Ancien dépôt de charbon sans enseigne, flamenco live presque tous les soirs, public mélangé et bohème. Sangria médiocre : prenez une bière ou un vin.",
    tip: "Entrée gratuite, concerts vers 22h–23h." },
  { id: "garlochi", cat: "nuit", name: "El Garlochí", area: "Centro", addr: "Calle Boteros 26",
    lat: 37.39049, lng: -5.98953,
    desc: "Bar baroque-kitsch entièrement décoré en chapelle de Semana Santa, encens et musique cofrade. Expérience unique.",
    order: "Le cocktail « Sangre de Cristo ». Ouvre tard." }
];

/* ---------------- PROGRAMME ---------------- */
const DAYS = [
  {
    key: "mer", label: "Mer 30", title: "Mercredi 30 septembre — Arrivée",
    mood: "Atterrissage en douceur, premier verre en terrasse.",
    items: [
      { time: "Soir", text: "Vol Toulouse → Séville. Taxi depuis l’aéroport (~20 min, tarif forfaitaire affiché ~25–30 € pour 4 — plus simple que le bus EA)." , place: null },
      { time: "Arrivée", text: "Installation à l’appartement. ⚠️ Prévenir l’hôte de l’heure d’arrivée (check-in normal 15h–20h).", place: "apt" },
      { time: "22h", text: "Premier dîner tardif (les Sévillans dînent à 21h30–22h30) : Bar Antojo ou Dúo Tapas, puis un verre sur l’Alameda.", place: "antojo" },
      { time: "Minuit", text: "Dernière copa sur la terrasse d’un bar de l’Alameda de Hércules.", place: "alameda" }
    ]
  },
  {
    key: "jeu", label: "Jeu 1", title: "Jeudi 1er octobre — Marché aux puces & quartiers nord",
    mood: "Le Séville des Sévillans : brocante, marché, palais, peña flamenca.",
    items: [
      { time: "9h00", text: "Café + tostada con tomate au comptoir d’un bar de la calle Feria.", place: null },
      { time: "9h30", text: "Mercadillo El Jueves sur la calle Feria — on flâne, on chine, on négocie (espèces).", place: "jueves" },
      { time: "11h30", text: "Caña + assiette de fruits de mer dans les bars du Mercado de Feria.", place: "feria_mkt" },
      { time: "12h30", text: "Palacio de las Dueñas, le palais des ducs d’Albe, à deux rues de l’appartement.", place: "duenas" },
      { time: "14h30", text: "Déjeuner-tapas au comptoir d’El Rinconcillo (1670).", place: "rinconcillo" },
      { time: "16h30", text: "Siesta ☀️ (on sera dehors tard).", place: "apt" },
      { time: "18h30", text: "Balade Casa de Pilatos (ou Basílica de la Macarena + murailles si on préfère rester au nord).", place: "pilatos" },
      { time: "19h30", text: "Coucher de soleil depuis les Setas de Sevilla.", place: "setas" },
      { time: "20h30", text: "Tertulia flamenca du jeudi à la Peña Torres Macarena — du flamenco pour aficionados, pas pour touristes.", place: "torresmac" },
      { time: "22h15", text: "Dîner chez Eslava (réservé !) — cigarro para Bécquer et costilla a la miel.", place: "eslava" }
    ]
  },
  {
    key: "ven", label: "Ven 2", title: "Vendredi 2 octobre — Alcázar & Noche en Blanco",
    mood: "Le grand monument le matin, siesta, puis la ville ouverte toute la nuit.",
    items: [
      { time: "9h15", text: "Churros con chocolate chez El Comercio (ou café rapide).", place: "comercio" },
      { time: "9h30", text: "Real Alcázar, premier créneau (billet réservé) — prévoir 2h30, ne pas rater les jardins.", place: "alcazar" },
      { time: "12h30", text: "Flânerie dans le Barrio Santa Cruz ; vermut chez Las Teresas ou à La Fresquita.", place: "teresas" },
      { time: "14h00", text: "Tournée de l’Arenal : montadito de pringá à la Bodeguita Romero, fino dans les tinajas de Casa Morales.", place: "romero" },
      { time: "15h30", text: "Promenade Torre del Oro → Maestranza le long du fleuve, puis siesta obligatoire.", place: "torreoro" },
      { time: "19h00", text: "🌙 Noche en Blanco (18h–2h) : suivre les activités réservées sur nocheenblanco.org (palais, Casa de Pilatos, Ayuntamiento, Salvador, concerts, routes nocturnes…).", place: "ayto" },
      { time: "21h30", text: "Pause dîner tapas entre deux visites : Blanco Cerrillo (boquerones) ou Kiko de la Chari selon le quartier.", place: "cerrillo" },
      { time: "23h30", text: "Flamenco à La Carbonería, ou cocktail « Sangre de Cristo » au Garlochí.", place: "carboneria" },
      { time: "Tard", text: "Retour à pied par l’Alameda.", place: "alameda" }
    ]
  },
  {
    key: "sam", label: "Sam 3", title: "Samedi 3 octobre — Cathédrale, Plaza de España, Triana",
    mood: "Le grand classique, un beau déjeuner, et un dernier verre à Triana.",
    items: [
      { time: "10h45", text: "Cathédrale & montée de la Giralda à l’ouverture (billet réservé) — ~1h15. Garder le billet pour l’église du Salvador.", place: "catedral" },
      { time: "12h15", text: "Apéro sur la Plaza del Salvador comme les Sévillans le samedi midi, visite express du Salvador.", place: "salvador" },
      { time: "13h45", text: "Déjeuner gastronomique chez Sobretablas (réservé) — accords vins de Jerez.", place: "sobretablas" },
      { time: "16h30", text: "Digestion au Parque de María Luisa puis Plaza de España.", place: "espana" },
      { time: "18h00", text: "Traversée vers Triana : Mercado, Calle Betis, dernier verre aux Golondrinas (ou caille chez Casa Ruperto).", place: "golondrinas" },
      { time: "Soir", text: "Récupérer les bagages, taxi pour l’aéroport (compter 25 min + marge). ¡Hasta pronto!", place: "apt" }
    ]
  }
];

/* ---------------- À RÉSERVER ---------------- */
const TODO = [
  { id: "t1", text: "Real Alcázar — vendredi 2/10, créneau 9h30 (4 billets, site officiel)", url: "https://alcazarsevilla.org/" },
  { id: "t2", text: "Cathédrale + Giralda — samedi 3/10, 10h45–11h (13 € en ligne)", url: "https://catedraldesevilla.servitickets.es/" },
  { id: "t3", text: "Eslava — dîner jeudi 1/10 vers 22h (954 90 65 68)", url: "https://espacioeslava.com/reserva-restaurante/" },
  { id: "t4", text: "Sobretablas — déjeuner samedi 3/10, 13h45", url: "https://sobretablasrestaurante.com/" },
  { id: "t5", text: "Noche en Blanco — réserver les activités payantes/limitées (dès publication du programme)", url: "https://nocheenblanco.org/" },
  { id: "t6", text: "Prévenir l’hôte de l’heure d’arrivée mercredi soir", url: null },
  { id: "t7", text: "Setas de Sevilla — billet coucher de soleil jeudi (facultatif)", url: null },
  { id: "t8", text: "Retirer un peu d’espèces (marché du jeudi, petits bars)", url: null }
];
